services:
  - type: "worker" 
    name: msrp-systems
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    autoDeploy: true

